### ISSUE TITLE
MESSY CSS

### ISSUE THREAD

**Issue by mardenrafael** [mardenrafael/pokedex#11]
O arquivo index.css esta uma **bagunça**

![image](https://user-images.githubusercontent.com/69557606/182746857-037f5c1c-d281-45ec-8e23-d0f3ca23129c.png)

![image](https://user-images.githubusercontent.com/69557606/182746891-0e946421-2478-48a6-bc17-d8d3210ed0d6.png)

![image](https://user-images.githubusercontent.com/69557606/182746926-b4d9089b-66a2-4624-ab62-1f760904608b.png)
 
![image](https://user-images.githubusercontent.com/69557606/182746955-6e4e1fb5-4478-4585-817e-1b78ed633fc6.png)

![image](https://user-images.githubusercontent.com/69557606/182746995-6c169d47-ba35-48b8-8af9-7b5984d957af.png)

![image](https://user-images.githubusercontent.com/69557606/182747011-6c7aa4f3-3ee5-4348-bf2c-22018a4a14fc.png)

![image](https://user-images.githubusercontent.com/69557606/182747025-ded53709-3f53-457c-8c8d-edd61ad45078.png)

**In my opinion, we have more than a hundred lines of css completely messed up, we have to think about how to better organize this css to facilitate organization and maintenance**

**Comment by magnojunior07** [comment]
**SUGGESTION FOR BETTER ORGANIZATION OF CSS**

For a better organization of the css, it would be interesting to organize it in different files, specifying what each file does, reducing the number of lines in the css file, and making it more organized and easier to solve any eventual problem.

![print1](https://user-images.githubusercontent.com/99290062/183109578-e15a3515-eff3-4f8c-9880-3cd7b1815e94.png)
![print2](https://user-images.githubusercontent.com/99290062/183109586-7c12fff3-124e-4670-981f-1c6c7f28c640.png)
![print3](https://user-images.githubusercontent.com/99290062/183109588-64c273e1-1a41-40dc-9feb-f77b99585299.png)
![print4](https://user-images.githubusercontent.com/99290062/183109590-69143e2a-f9b6-436d-81f7-1e5e74d8a8b8.png)
![print5](https://user-images.githubusercontent.com/99290062/183109592-27538983-c91f-4f07-a586-7c6d7b6d61c9.png)
![print6](https://user-images.githubusercontent.com/99290062/183109594-30ca95b4-39e3-4497-a4b1-3306e3646506.png)

I believe that this way the css would be much more organized and readable, facilitating the resolution of an eventual problem.
@mardenrafael

**Comment by mardenrafael** [comment]
I agree, separating the css files will help to keep the organization and will make the maintenance much easier.

But the method you used to import a css file into another css file, not useful like that, because a css file is not depends on the other to work well, so I don't see the need to import one into another, but import them all into HTML.

@magnojunior07
